# Generated by Django 5.2.8 on 2025-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
