# Generated by Django 5.2.8 on 2025-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=10)),
                ('fila', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
