# Generated by Django 5.2.8 on 2025-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='fila',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='via',
            field=models.CharField(max_length=20),
        ),
    ]
