# Generated by Django 5.2.8 on 2025-12-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_senha_temporaria_cliente_senha'),
        ('tentativas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativaacesso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='tentativaacesso',
            name='sucesso',
            field=models.BooleanField(default=False),
        ),
    ]
