# Generated by Django 5.2.8 on 2025-12-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_senha_temporaria_cliente_senha'),
        ('locacao', '0001_initial'),
        ('pagamentos', '0002_alter_pagamento_data_pagamento_and_more'),
        ('veiculos', '0002_alter_veiculo_estacionamento_alter_veiculo_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='metodo_verificacao',
        ),
        migrations.AddField(
            model_name='locacao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagamentos.pagamento'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='veiculos.veiculo'),
        ),
    ]
