# Generated by Django 5.2.8 on 2025-11-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('km', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.estacionamento')),
            ],
        ),
    ]
