# Generated by Django 5.2.8 on 2025-12-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_alter_estacionamento_descricao_and_more'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='estacionamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacionamento.estacionamento'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='km',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(default='disponivel', max_length=20),
        ),
    ]
