# Generated by Django 5.2.8 on 2025-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha_temporaria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
